apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Chart.Name "deployment" | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
    spec:
      containers:
    {{- if .Values.image.digest }}
      - image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
    {{- else }}
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    {{- end }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: "{{ .Chart.Name }}"
        ports:
        - containerPort: 8081
