apiVersion: v1
kind: Service
metadata:

  name: {{ printf "%s-%s" .Chart.Name "service" | quote }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: "{{ .Chart.Name }}"